# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[2.8788e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [24]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3688, 0.2972, 0.5631],
        [0.4535, 0.7039, 0.6346],
        [0.0251, 0.5794, 0.5328],
        [0.0027, 0.5575, 0.0485],
        [0.7427, 0.5577, 0.8731]])


Get its size

In [25]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [26]:
x[1:3] = 2
print(x)

tensor([[0.3688, 0.2972, 0.5631],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.0027, 0.5575, 0.0485],
        [0.7427, 0.5577, 0.8731]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [17]:
z = torch.Tensor(2, 17)
print(z)

tensor([[2.8887e-35, 0.0000e+00, 2.2141e-43, 0.0000e+00,        nan, 0.0000e+00,
         4.8222e+30, 4.4166e+21, 8.4830e+26, 2.1712e+29, 7.1941e+28, 1.0383e-05,
         1.8491e+31, 2.7691e+20, 1.0645e+24, 5.5603e+31, 4.2964e+24],
        [1.0765e+21, 1.0765e+21, 4.4721e+21, 2.8147e+29, 7.5261e+28, 9.1592e+08,
         3.5562e-09, 1.7743e+28, 9.9302e+05, 2.7946e+20, 6.0609e+01, 3.3389e-09,
         4.6304e+27, 7.2151e+22, 2.6800e+20, 2.1195e+11, 1.5226e+19]])


In [18]:
z = torch.FloatTensor(3, 1)
print(z)

tensor([[8.9943e-35],
        [0.0000e+00],
        [2.3694e-38]])


In [19]:
z = torch.LongTensor(5, 2, 1)
print(z)

tensor([[[          111853184],
         [                 93]],

        [[         4294967295],
         [7165064483209180463]],

        [[8083788061079465057],
         [3976172070423262329]],

        [[7021161797246346287],
         [8372037111668370275]],

        [[7091318039142167151],
         [7165912502757846063]]])


In [20]:
z[:] = 7
print(z)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [21]:
z = torch.ByteTensor(5,)
print(z)

tensor([ 64,  28, 239,   6,   0], dtype=torch.uint8)


In [22]:
z[:] = 0
z[1:4] = 1
print(z)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [27]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3531, 0.9486, 0.6964],
        [2.8264, 2.9607, 2.5879],
        [2.8894, 2.0053, 2.0602],
        [0.5704, 0.8167, 0.5482],
        [1.1569, 0.9274, 1.4768]])


### 2.2 Addition: syntax 2

In [28]:
print(torch.add(x, y))

tensor([[1.3531, 0.9486, 0.6964],
        [2.8264, 2.9607, 2.5879],
        [2.8894, 2.0053, 2.0602],
        [0.5704, 0.8167, 0.5482],
        [1.1569, 0.9274, 1.4768]])


### 2.3 Addition: giving an output tensor

In [29]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3531, 0.9486, 0.6964],
        [2.8264, 2.9607, 2.5879],
        [2.8894, 2.0053, 2.0602],
        [0.5704, 0.8167, 0.5482],
        [1.1569, 0.9274, 1.4768]])


### 2.4 Addition: in-place

adds `x`to `y`

In [30]:
y.add_(x)
print(y)

tensor([[1.3531, 0.9486, 0.6964],
        [2.8264, 2.9607, 2.5879],
        [2.8894, 2.0053, 2.0602],
        [0.5704, 0.8167, 0.5482],
        [1.1569, 0.9274, 1.4768]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [31]:
print(x[:, 1])

tensor([0.2972, 2.0000, 2.0000, 0.5575, 0.5577])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [44]:
z1 = torch.rand(5, 3)
z2 = torch.rand(5, 3)
print(z1)
print(z2)

tensor([[0.5043, 0.1441, 0.9220],
        [0.8902, 0.5709, 0.2585],
        [0.6135, 0.6084, 0.7985],
        [0.4950, 0.5812, 0.9725],
        [0.0567, 0.8597, 0.1995]])
tensor([[0.4589, 0.2471, 0.0285],
        [0.1472, 0.3545, 0.1738],
        [0.4134, 0.3721, 0.8132],
        [0.6385, 0.8559, 0.7788],
        [0.7040, 0.4872, 0.9857]])


In [51]:
# 1.
z3 = z1.mul(z2)
print(z3)

tensor([[0.2314, 0.0356, 0.0262],
        [0.1310, 0.2024, 0.0449],
        [0.2536, 0.2264, 0.6493],
        [0.3160, 0.4974, 0.7574],
        [0.0399, 0.4189, 0.1967]])
tensor([[0.2314, 0.0356, 0.0262],
        [0.1310, 0.2024, 0.0449],
        [0.2536, 0.2264, 0.6493],
        [0.3160, 0.4974, 0.7574],
        [0.0399, 0.4189, 0.1967]])


In [48]:
# 2.
z1_copy = z1.clone()
z1_copy.mul_(z2)
print(z1_copy)

tensor([[0.2314, 0.0356, 0.0262],
        [0.1310, 0.2024, 0.0449],
        [0.2536, 0.2264, 0.6493],
        [0.3160, 0.4974, 0.7574],
        [0.0399, 0.4189, 0.1967]])


In [49]:
# 3
torch.div(z1, z2, out=z3)
print(z3)

tensor([[ 1.0990,  0.5833, 32.3824],
        [ 6.0472,  1.6105,  1.4873],
        [ 1.4839,  1.6350,  0.9819],
        [ 0.7753,  0.6790,  1.2488],
        [ 0.0806,  1.7645,  0.2024]])


In [55]:
# 4
z4 = torch.rand(4, 2)
z5 = torch.rand(2, 4)

z6 = torch.matmul(z4, z5, out=z3.resize_(0))
print(z3)
print(z3.shape)

tensor([[0.7571, 0.1711, 1.0420, 0.2979],
        [0.3617, 0.0963, 0.4338, 0.2510],
        [0.7550, 0.1793, 1.0010, 0.3619],
        [0.3487, 0.0891, 0.4347, 0.2142]])
torch.Size([4, 4])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [56]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [57]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [58]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [59]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [61]:
# 1
z1 = torch.ones([5, 2])
print(z1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [63]:
# 2
z1_np = z1.numpy()
print(z1_np)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [64]:
# 3
z1_np_torch = torch.from_numpy(z1_np)
print(z1_np_torch)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [60]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.3688, 0.2972, 0.5631],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.0027, 0.5575, 0.0485],
        [0.7427, 0.5577, 0.8731]], device='cuda:0')
tensor([[1.3531, 0.9486, 0.6964],
        [2.8264, 2.9607, 2.5879],
        [2.8894, 2.0053, 2.0602],
        [0.5704, 0.8167, 0.5482],
        [1.1569, 0.9274, 1.4768]], device='cuda:0')
tensor([[1.7219, 1.2458, 1.2595],
        [4.8264, 4.9607, 4.5879],
        [4.8894, 4.0053, 4.0602],
        [0.5731, 1.3742, 0.5966],
        [1.8996, 1.4851, 2.3500]], device='cuda:0')
